# This is a basic workflow to help you get started with Actions

name: Test datadog sourcemaps uploading

# allows manually trigger the workflow
on:
  workflow_dispatch:

jobs:
  pre-build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install deps
        run: npm ci

      - name: test datadog sourcemaps
        env:
          DATADOG_API_KEY: ${{secrets.DATADOG_API_KEY}}
          DATADOG_APP_KEY: ${{secrets.DATADOG_APP_KEY}}
        run: |
          TEMP_DIR=$(mktemp -d)
          echo '{}' > $TEMP_DIR/fake.js
          echo '{"version":3,"file":"out.js","sourceRoot":"","sources":["fake.js"],"names":["src"],"mappings":"AAgBC"}' > $TEMP_DIR/fake.js.map
          npx @datadog/datadog-ci sourcemaps upload $TEMP_DIR/ --service test_datadog-ci --release-version 0.0.1 --minified-path-prefix https//fake.website
          rm -rf $TEMP_DIR
