# This is a basic workflow to help you get started with Actions

name: Test datadog sourcemaps uploading

# allows manually trigger the workflow
on:
  workflow_dispatch:

jobs:
  pre-build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install deps
        run: npm ci

      - name: run script
        run: |
          echo 'hello cruel world'
