name: Master concurrency check

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: havenchyk/gha-playground/./github/actions/composite
      - name: checkout
        uses: actions/checkout@v2

      - name: install deps
        run: npm ci

      - name: print context variables
        run: |
          echo hello, world
          echo ${{github.workflow}}-${{ github.head_ref }}
          echo end
